apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: uyi9zlvps-dotnet-basic-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/uyi9zlvps-dotnet-basic